### ISSUE TITLE
[MacOS 10.15] MacOS Catalina File Directory

### ISSUE THREAD

**Issue by Ashteroide** [Waitsnake/AnimatedGif#59] opened 2019-10-16 22:13 UTC
After repeatedly spamming the 'Select file or Directory' it still would not allow me to select a file, my macOS is Catalina 10.15, I have used this on Mojave and it works, please review as to why it's not working, I need my dancing cat GIF wallpaper (There's also a video to show what happens(not really useful and I can't upload it))

**Comment by ShinJJang** [comment] 2019-10-18 04:53
It is related with sandbox introduced in 10.15 Catalina.
There is same issue to another screen saver app, [Aerial](https://github.com/JohnCoates/Aerial)

https://github.com/JohnCoates/Aerial/pull/864/commits/813c8b5587165b531740a6c5d092c17549310b87

![붙여넣은_이미지_2019__10__18__오후_1_52](https://user-images.githubusercontent.com/1948695/67066695-9b15a000-f1ae-11e9-883a-9a6ed83dc9d1.png)

**Comment by Waitsnake** [comment] 2019-10-18 20:46
Yes, Apple has sandboxed the system service for screensavers in witch screensavers are running and that are elementary necessary for them to work. A screensaver is no own program in macOS it is only a kind of plug-in. And as long as the Apple system service for screensavers has not the right from the operating system that a user can select or open his own files also a plug-in did not have this rights.

I don't know where the road is going for screensavers in macOS at the moment(?) and I can only assume Apple was doing/planing a complete change in the Screensaver-API, but they did not get it finish for the release date of Catalina and stopped pretty much the rebuilding in the middle of the work and expose the building ruin to the weather and elements as it was.

It just makes no sense for me at the moment to spent any time into this hobby project as long as Apple has not finish their work and document the new concepts properly to the programmers if they're any.

Sorry there is no support of AnimatedGif for Catalina as there is no appropriate support of Apple for screensavers.

**Comment by Waitsnake** [comment] 2020-02-16 00:34
I will close this issue as this is an duplicate of #57 .

**Closed as completed by Waitsnake** 2020-02-16 00:34 UTC
Labels: duplicate, Catalina
