### ISSUE TITLE
Background color doesn't match GIF using color picker.

### ISSUE THREAD

**Issue by shamesung** [Waitsnake/AnimatedGif#4] opened 2016-02-07 10:51 UTC
![2016-02-07-04h49m38s635](https://cloud.githubusercontent.com/assets/6269751/12871942/68addd2e-cd56-11e5-82bd-32f1b9a8ba12.png)

**Comment by Waitsnake** [comment] 2016-02-07 11:10
Probably something differs with the color models used by texture loading function (glTexImage2D) and the background filling function (glClearColor) ? 
So can you send me the gif file (that I can take a look into the file for the color with an picture program) and tell me the color you picked up. And how you picked the color up, since the color picker window offers a lot of different ways to choose a color.

**Comment by Waitsnake** [comment] 2016-02-07 19:16
With an reverse image search I could found your image here [from http://flrn.nl/](http://flrn.nl/gifs/).
This image uses a normal RBG model and works a fine on my computer with no wrong colors and if I change the "color of the borders" around the GIF to the same value (Red=38, Green=38 and Blue=38) that I readout with a picture program like Pixelmator the borders and the background of the GIF looks same here.
You seems to use as border color (the only think you can change in the screensaver) of dark black (R=0,G=0 and B=0) while the GIF has much lighter black (R=38, G=38 and B=38).

So maybe you just forgot to save your change in the color picker with pressing the "OK" button?

Go to "Background color:" and open color picker -> select second plane where you can choose color values by numbers -> choose "RGB" -> Enter the values 38 for Red, Green and Blue -> press the "OK" Button on the screensaver config window.

Or maybe do you expect the screensaver to change the colors inside the GIF? This can of cause not done since a screensaver is no picture editing tool and has no idea which color is the background, light blue, dark green, egg yellow? Well what will be possible if your GIF uses an alpha channel that defines what is transparent in the picture, so that the background/border color can shine thru, but you GIF has NO alpha channel.

Look here is a GIF example with an alpha channel:
[bowserspin](http://stillavailable.com/max/bowserspin.gif)

While I try out the alpha channel GIF for my self I saw that the alpha channel works only in preview mode, but in the OpenGL fullscreen was not working. So I fix the alpha channel in OpenGL for fullscreen mode (see last checkin).

**Comment by shamesung** [comment] 2016-02-07 21:09
I'm using the color picker in the options of the screensaver. I did click ok.
Im guessing since the color picker samples the color from the preview. The preview colors are not accurate..
[Color.mov.zip](https://github.com/Stino/AnimatedGif/files/120917/Color.mov.zip)

**Comment by shamesung** [comment] 2016-02-07 21:10
I tried sampling the color directly by opening the GIF in preview application. But still the same..

**Comment by Waitsnake** [comment] 2016-02-07 23:03
If you pick the color directly from the GUI as you did than color shows you a value that is transformed by your color profile (ICC file) that you set for your LCD or monitor in the system preferences.

I try different setups to pickup the color:
1.) get original color from file with using color picker of **Pixelmator** -> R=38, G=38, B=38
-> enter the values manually in the color window of screensaver with **typing in the numbers by hand**
-> run screensaver and all colors look fine
2.) get original color from file with using color picker of **Gimp** -> R=38, G=38, B=38
-> enter the values manually in the color window of screensaver with **typing in the numbers by hand**
-> run screensaver and all colors look fine
3.) set the color profile of my monitor in system preferences to default "Farb-LCD" (german for "Color-LCD") 
I use the color picker in screensaver to pickup the GUI colors of OSX as you did -> R=38, G=38, B=38 
_(if you left the colored pencil view and change to RGB view before picking up colors you see the numbers)_
-> run screensaver and all colors look fine
4.) set the color profile of my monitor in system preferences to "Apple RGB" 
I use the color picker in screensaver to pickup the GUI colors of OSX as you did -> R=28, G=28, B=28 
-> run screensaver and but now have different colors as you had
5.) set the color profile of my monitor in system preferences to a self made one "MBA 11 native22 9cf2" 
I use the color picker in screensaver to pickup the GUI colors of OSX as you did -> R=41, G=41, B=41 
-> run screensaver and but now have different colors as you had

This shows clear to me that the problem is that if you pick up the color directly from the GUI and not from the file itself. The color profile (ICC) function active in OSX transforms the colors you pick from the GUI.
Since the color picker of the screensaver is also part of OSX operating system (called **NSColorWell** class) and the screensaver can only receive as result the selected color from this class and has no influence if the class take the active color profile into account or not. There is nothing I can do, sorry.

So I think we can close this issue since it is no problem of AnimatedGif but an problem of the operating system OSX. You should report this bug against **NSColorWell** if you wish that it will be solved.

[Bug Reporter](https://developer.apple.com/bug-reporting/)

**Closed as completed by Waitsnake** 2016-02-07 23:03 UTC
Labels: wontfix
