### ISSUE TITLE
Can't select a (gif) file

### ISSUE THREAD

**Issue by tom-van-pelt** [Waitsnake/AnimatedGif#60] opened 2019-10-22 09:35 UTC
If I click on the button 'Select File or Directory' nothing happens. I'm running the latest version (version 1.5.3) on macOS Catalina (version 10.15).  iMac i'm using is from late 2013. 
Thanks in advance for helping.

**Comment by Waitsnake** [comment] 2019-10-24 06:31
Apple has sandboxed the system service for screensavers in witch screensavers are running and that are elementary necessary for them to work. A screensaver is no own program in macOS it is only a kind of plug-in. And as long as the Apple system service for screensavers has not the right from the operating system that a user can select or open his own files also a plug-in like AnimatedGif did not have this rights.

Sorry, there is **no support of AnimatedGif for Catalina** as long there is no appropriate support of Apple for screensavers.

I will close this issue as this is an duplicate of #59 . For more detail you can see at #57 and #59 .

**Closed as completed by Waitsnake** 2019-10-24 06:31 UTC
Labels: duplicate, Catalina
