### ISSUE TITLE
[MacOS 10.13.6] saver window

### ISSUE THREAD

**Issue by diboandrews** [Waitsnake/AnimatedGif#38] opened 2018-09-02 17:37 UTC
Having downloaded the Animated Gif as screensaver, I now have a "Saver Window" that is always on my screen. Have tried to get rid of it to no success. It interferes with all activities. Can you advise.
diboandrews06@gmail.com

**Comment by Waitsnake** [comment] 2018-09-04 21:55
Actually I have no idea. Nobody before reports such an issue before. Can you upload a screenshot? 
Witch version of macOS do you use? I would guess it is the newest 10.14 Beta 9 or I'm wrong?

The program is currently not compatible with any version of 10.14 Mojave and you can't use AnimatedGif with it. Apple still changes a lot in the API of file operations (see #37 ) and screensaver engine itself between the different versions of the beta and so there is no stable basis for screensaver development at the moment.

The only workaround that I could imagine at the moment is to detect the OS version of 10.14 Mojave, open a message box that says that the screensaver is not compatible with 10.14 and than close the screensaver.

**Comment by diboandrews** [comment] 2018-09-06 19:23
Thank you for the reply.  I use a Mac OS High Sierra Version 10.13.6 The “Saver Window” which is the problem, still sits on the screen and cannot be removed. In fact, it interferes with some activities and is a nightmare. Hope we can find a solution to this issue.

**Comment by Waitsnake** [comment] 2018-09-06 20:32
Good to know at least major version with the issue. I will put the version into the issue title.
According to Wikipedia there are 3 sub versions of 10.13.6 and I assume you just use the newest 17G2307 from 28. August 2018.

Actually I'm still using 10.11.6 El Capitan thats why I'm not see new issues caused by new OS updates from Apple when they appear. AnimatedGif had issues before with 10.13.4 but I could fix them with AnimatedGif 1.3.7. But installing High Sierra on my Mac and restoring it afterwards from Time Machine Backup to El Capitan is always a big time consuming hassle.

Back to the problem. I still not quite sure that I really understand what you mean with "Saver window", but maybe we can find it out.

The screensaver AnimatedGif has two different modes and one configuration panel inside the system configuration.
Mode one is the normal screensaver fullscreen mode where you just select AnimatedGif as screensaver and when you not use mouse or keyboard a while or if you use active corners it will start.
Mode two is the background mode that should be visible as desktop. You can enable or disable the background mode in the screensaver configuration panel. [See here under "Setup - Mac" how to get there. Option Panel is opened at point 5.](https://github.com/Waitsnake/AnimatedGif).
There is an option called "Run screen saver in background (launch agent)" that can be set to "load" and "unload".

Try to press here "unload" to hopefully stop your "Saver window". If this works that means background mode is broken again with 10.13.6 and I'm not sure if this can be fixed in future or not since there is no official API for an background mode of screensavers from Apple. But I hope you can at least stop this "Saver window".

The background mode uses Apples Screensaver Engine. In older MacOS versions that worked simple by a parameter named "-background" but with High Sierra Apple has brocken that parameter. The workaround for High Sierra was than to use the option "-window" witch runs a screensaver in a foreground window and is normally used for debugging. With the normal window API I changed this foreground window into an borderless background window. I assume the mechanism is broken with 10.13.6 for what ever reason. I'm not sure when I will find time to install High Sierra again to debug this.

**Comment by Waitsnake** [comment] 2018-09-06 20:32
Back to the problem. I still not quite sure that I really understand what you mean with "Saver window", but maybe we can find it out.

The screensaver AnimatedGif has two different modes and one configuration panel inside the system configuration.
Mode one is the normal screensaver fullscreen mode where you just select AnimatedGif as screensaver and when you not use mouse or keyboard a while or if you use active corners it will start.
Mode two is the background mode that should be visible as desktop. You can enable or disable the background mode in the screensaver configuration panel. [See here under "Setup - Mac" how to get there. Option Panel is opened at point 5.](https://github.com/Waitsnake/AnimatedGif).
There is an option called "Run screen saver in background (launch agent)" that can be set to "load" and "unload".

Try to press here "unload" to hopefully stop your "Saver window". If this works that means background mode is broken again with 10.13.6 and I'm not sure if this can be fixed in future or not since there is no official API for an background mode of screensavers from Apple. But I hope you can at least stop this "Saver window".

The background mode uses Apples Screensaver Engine. In older MacOS versions that worked simple by a parameter named "-background" but with High Sierra Apple has brocken that parameter. The workaround for High Sierra was than to use the option "-window" witch runs a screensaver in a foreground window and is normally used for debugging. With the normal window API I changed this foreground window into an borderless background window. I assume the mechanism is broken with 10.13.6 for what ever reason. I'm not sure when I will find time to install High Sierra again to debug this.

**Comment by Waitsnake** [comment] 2018-10-31 00:17
Because someone asked on an other webpage for an automatic way to uninstall I experienced the same "saver window" issue on Mojave 10.14.1 .

**Possible reason one** is an incomplete uninstallation. You delete AnimatedGif without stopping the background mode first (in the screensaver panel with "unload" button). AnimatedGif creates an Launchd-Script that automatically start the ScreenSaverEngine of macOS in window mode. Only the screensaver AnimatedGif can change that window mode (a window with "saver window" in the title) to a real background mode. Other screensavers can not do that. When the Launchd script is still active the screensaver engine will start an other screensaver after a reboot or re-login that can not change the window mode into background mode and you will see an other screensaver in this "saver window".

To fix the incomplete uninstallation download the new uninstaller here and unzip it and run the program(stops and removes Launchd-Script): 
https://github.com/Waitsnake/AnimatedGif/raw/master/tools/Uninstall_AnimatedGif.app.zip

**Possible reason two** is that you start the background mode while AnimatedGif was your active screensaver. Than you change the screensaver to another screensaver. After an re-login or reboot the former mentioned Launchd-Script automatically start the ScreenSaverEngine of macOS in window mode with your new selected screensaver. The other screensaver can't change the window mode into background mode and you will see the other screensaver in this "saver window".

To fix this change back to the screensaver AnimatedGif and in the screensaver preference panel press on the "unload" button and than change afterwards back to your other screensaver of choice.

**Closed as completed by Waitsnake** 2018-10-31 00:17 UTC
Labels: help wanted
