### ISSUE TITLE
Could not Load Preferences plane.

### ISSUE THREAD

**Issue by Xardous** [Waitsnake/AnimatedGif#58] opened 2019-08-28 21:10 UTC
Comes up with an error which says, Could not load Desktop & Screen Saver preference pane. Occurs when trying to install the saver file.
Thanks

**Comment by Waitsnake** [comment] 2019-08-29 18:15
What is the exact version number of your operating system?

What version of AnimatedGif do you use?

What kind of Mac Hardware do you use (model name, build year and what GPU is build in)?

**Comment by Waitsnake** [comment] 2019-08-29 19:18
I start googling about the error message and this issues happens all the time over the years to random Mac users at least since Leopard times back in 2008 (at this time the screensaver AnimatedGif was not even developed. I started at end of 2015.).

Here just a few search results around this topic thatI found.

2008 (Leopard):
https://discussions.apple.com/thread/1521783
https://discussions.apple.com/thread/1435850

2011 (Lion):
https://discussions.apple.com/thread/3349669

2012 (Mountain Lion):
https://discussions.apple.com/thread/3816737
https://discussions.apple.com/thread/4219538

2014 (Mavericks):
https://discussions.apple.com/thread/6661736
https://discussions.apple.com/thread/6752068

2015 (Yosemite):
https://discussions.apple.com/thread/6764678
https://apple.stackexchange.com/questions/180083/preferences-error-on-imac-yosemite-10-10-2

2019 (Mojave):
https://discussions.apple.com/thread/250254832
https://www.reddit.com/r/applehelp/comments/bmkxei/help_desktop_background_issue/
https://discussions.apple.com/thread/8551803

The cause was never related to any screensavers itself but in most cases to corrupted preferences files of the operating system itself. 

In one case a corrupt desktop picture (jpg) was the cause (see the [stackexchange-link](https://apple.stackexchange.com/questions/180083/preferences-error-on-imac-yosemite-10-)).

So it sounds for me more like a coincident that the operation system creates a corrupt preference file when you play around with AnimatedGif.

But whatever the cause of your issue was you can completely uninstall AnimatedGif if you think it is related. In the project [readme](https://github.com/Waitsnake/AnimatedGif) I described many different ways to uninstall AnimatedGif and also linked an [automatic uninstaller](https://github.com/Waitsnake/AnimatedGif/raw/master/tools/Uninstall_AnimatedGif.app.zip).

**Comment by Xardous** [comment] 2019-09-06 10:37
Thank you for your response, but the only way I found to fix the error was the remove a file called desktoppicture.db in my Dock folder (in Application Support folder), and then restarting my mac completely. 
My mac specs : MacBook Air (11-inch, Early 2015) , 8 GB 1600 MHz DDR3, Intel HD Graphics 6000 1536 MB.

**Comment by Waitsnake** [comment] 2019-09-08 08:54
Glad to hear you solved your problem.
Your solution of removing the file desktoppicture.db matches with the problem of the corrupt desktop picture (jpg) from [stackexchange](https://apple.stackexchange.com/questions/180083/preferences-error-on-imac-yosemite-10-10-2). Since AnimatedGif never even touches this file nor doing something to the Dock-Application I close this issue now.

**Closed as completed by Waitsnake** 2019-09-08 08:54 UTC
Labels: help wanted
